//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.11 at 12:37:05 AM CEST 
//


package edu.campuswien.se.carrental.currencyconverter.dto;

public enum CurrencyEnum {
    EUR,
    USD,
    GBP,
    JPY,
    BGN,
    CZK,
    DKK,
    HUF,
    PLN,
    RON,
    SEK,
    CHF,
    ISK,
    NOK,
    HRK,
    RUB,
    TRY,
    AUD,
    BRL,
    CAD,
    CNY,
    HKD,
    IDR,
    ILS,
    INR,
    KRW,
    MXN,
    MYR,
    NZD,
    PHP,
    SGD,
    THB,
    ZAR;

    public String value() {
        return name();
    }

    public static CurrencyEnum fromValue(String v) {
        return valueOf(v);
    }

}
